// src/competitive.js
//
// Competitive Expansion SOW (SDK-001): thin, stateless REST clients for the organization-scoped public API (/api/public/v1/*, Bearer inaya_... key).
// Same per-call {baseUrl, apiKey, ...} style as TrustPlatform: no hidden config, no singleton. Namespaces:
//   Shares, FileRequests, Governance, Devices, Compliance (evidence + audit verify), Webhooks (receiver-side signature verification).
//
// WHAT IS DELIBERATELY NOT HERE
//   Secure Chat, Contacts and Secure Notes are end-to-end encrypted: their keys live in a person's browser or device and are never sent to the server, so a
//   Bearer API key cannot read or write them and no wrapper can honestly be offered. Likewise a file request cannot be CREATED over the API (its key pair
//   must be generated by a person's browser); it can be listed, inspected and revoked. No call here ever returns file content or a private key.
//   Feature-flagged areas answer with a 403/404 and an explanatory error while the feature is off for the organization.

import { InayaValidationError, InayaNetworkError, translateError } from "./errors.js";

const base = (baseUrl) => { if (!baseUrl) throw new InayaValidationError("baseUrl is required."); return baseUrl.replace(/\/$/, ""); };
const need = (v, name) => { if (!v) throw new InayaValidationError(`${name} is required.`); };
const e1 = encodeURIComponent;
const enc = new TextEncoder();
const hex = (buf) => [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, "0")).join("");
async function hmacHex(secret, data) {
  const key = await globalThis.crypto.subtle.importKey("raw", enc.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  return hex(await globalThis.crypto.subtle.sign("HMAC", key, enc.encode(data)));
}
function sameString(a, b) { if (a.length !== b.length) return false; let d = 0; for (let i = 0; i < a.length; i++) d |= a.charCodeAt(i) ^ b.charCodeAt(i); return d === 0; }
const qs = (o = {}) => { const p = new URLSearchParams(); for (const [k, v] of Object.entries(o)) if (v !== undefined && v !== null && v !== "") p.set(k, String(v)); const s = p.toString(); return s ? `?${s}` : ""; };

async function call({ baseUrl, apiKey, method = "GET", path, body }) {
  const root = base(baseUrl);
  need(apiKey, "apiKey (an inaya_... key)");
  const headers = { Authorization: `Bearer ${apiKey}` };
  if (body !== undefined) headers["Content-Type"] = "application/json";
  let res;
  try { res = await fetch(`${root}/api/public/v1/${path}`, { method, headers, ...(body !== undefined ? { body: JSON.stringify(body) } : {}) }); }
  catch (err) { throw translateError(err, "inaya-api"); }
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw Object.assign(new InayaNetworkError(data.error || `Request failed (${res.status}).`, { operation: "inaya-api" }), { status: res.status, code: data.code });
  return data;
}

export const Shares = {
  /** Every share in the organization. status: active | expired | revoked | exhausted. */
  list: ({ baseUrl, apiKey, status, documentId, limit, before }) => call({ baseUrl, apiKey, path: `shares${qs({ status, documentId, limit, before })}` }),
  /** A link share. `expiresAt` is required (ISO). Returns { shareId, token, share }; the token is shown once. */
  createLink: ({ baseUrl, apiKey, documentId, expiresAt, options }) => { need(documentId, "documentId"); need(expiresAt, "expiresAt"); return call({ baseUrl, apiKey, method: "POST", path: "shares", body: { documentId, expiresAt, options } }); },
  /** A share with a person already in the organization. permission: view | download | edit (see the share policy). */
  createMember: ({ baseUrl, apiKey, documentId, memberEmail, permission, expiresAt }) => { need(documentId, "documentId"); need(memberEmail, "memberEmail"); need(permission, "permission"); return call({ baseUrl, apiKey, method: "POST", path: "shares", body: { documentId, memberEmail, permission, expiresAt } }); },
  accessEvents: ({ baseUrl, apiKey, shareId, limit, before }) => { need(shareId, "shareId"); return call({ baseUrl, apiKey, path: `shares/${e1(shareId)}${qs({ limit, before })}` }); },
  revoke: ({ baseUrl, apiKey, shareId }) => { need(shareId, "shareId"); return call({ baseUrl, apiKey, method: "DELETE", path: `shares/${e1(shareId)}` }); },
};

export const FileRequests = {
  list: ({ baseUrl, apiKey, status, limit, before }) => call({ baseUrl, apiKey, path: `file-requests${qs({ status, limit, before })}` }),
  /** The request and its upload list (metadata only). */
  get: ({ baseUrl, apiKey, requestId }) => { need(requestId, "requestId"); return call({ baseUrl, apiKey, path: `file-requests/${e1(requestId)}` }); },
  revoke: ({ baseUrl, apiKey, requestId }) => { need(requestId, "requestId"); return call({ baseUrl, apiKey, method: "DELETE", path: `file-requests/${e1(requestId)}` }); },
};

export const Governance = {
  /** type: dlp | classification | metadata | upload | sharing | ... (as in the app). Read-only. */
  listPolicies: ({ baseUrl, apiKey, type, status }) => call({ baseUrl, apiKey, path: `governance/policies${qs({ type, status })}` }),
  listDlpEvents: ({ baseUrl, apiKey, decision, action, limit, before }) => call({ baseUrl, apiKey, path: `governance/dlp-events${qs({ decision, action, limit, before })}` }),
  classificationHistory: ({ baseUrl, apiKey, documentId, limit }) => { need(documentId, "documentId"); return call({ baseUrl, apiKey, path: `classification/${e1(documentId)}${qs({ limit })}` }); },
  /** Evaluates the organization's rules against the document's metadata. dryRun defaults to true: nothing changes unless you pass dryRun: false. */
  classify: ({ baseUrl, apiKey, documentId, dryRun = true }) => { need(documentId, "documentId"); return call({ baseUrl, apiKey, method: "POST", path: `classification/${e1(documentId)}`, body: { dryRun } }); },
};

export const Devices = {
  list: ({ baseUrl, apiKey }) => call({ baseUrl, apiKey, path: "devices" }),
  get: ({ baseUrl, apiKey, deviceId }) => { need(deviceId, "deviceId"); return call({ baseUrl, apiKey, path: `devices/${e1(deviceId)}` }); },
  /** action: trust | untrust | block | unblock | revoke | signout | reauth | wipe_cache | disable_sync | enable_sync. wipe_cache clears the app's own local data only. */
  action: ({ baseUrl, apiKey, deviceId, action }) => { need(deviceId, "deviceId"); need(action, "action"); return call({ baseUrl, apiKey, method: "POST", path: `devices/${e1(deviceId)}`, body: { action } }); },
};

export const Compliance = {
  /** Readiness overview by NIST SP 800-53 family. Readiness only: never a certification. */
  summary: ({ baseUrl, apiKey }) => call({ baseUrl, apiKey, path: "compliance/summary" }),
  controls: ({ baseUrl, apiKey, family, implementation, evidence, responsibility, owner, q }) => call({ baseUrl, apiKey, path: `compliance/controls${qs({ family, implementation, evidence, responsibility, owner, q })}` }),
  /** The tamper-evident trail for one record. */
  evidence: ({ baseUrl, apiKey, recordType, recordId }) => { need(recordType, "recordType"); need(recordId, "recordId"); return call({ baseUrl, apiKey, path: `evidence${qs({ recordType, recordId })}` }); },
};

export const Webhooks = {
  /**
   * Receiver-side verification of an Inaya webhook. Pass the RAW request body string and the x-inaya-signature header ("t=<ts>,v1=<hex>[,v1=<hex>]").
   * During a secret rotation the header carries two v1 values; either matches. Rejects anything older than `toleranceSeconds` (default 300) to stop replays.
   * Resolves true / false; a bad signature never throws (a missing secret or body does).
   */
  async verify({ secret, rawBody, signatureHeader, toleranceSeconds = 300, now = Date.now() }) {
    need(secret, "secret"); need(typeof rawBody === "string" ? rawBody : null, "rawBody (string)");
    const parts = String(signatureHeader || "").split(",").map((s) => s.trim());
    const t = parts.find((p) => p.startsWith("t="))?.slice(2);
    const sigs = parts.filter((p) => p.startsWith("v1=")).map((p) => p.slice(3));
    if (!t || !sigs.length || !/^\d+$/.test(t)) return false;
    if (Math.abs(now / 1000 - Number(t)) > toleranceSeconds) return false;
    const expected = await hmacHex(secret, `${t}.${rawBody}`);
    return sigs.some((x) => sameString(x, expected));
  },
};
